### ISSUE TITLE
Avro support?

### ISSUE THREAD

**Issue by rgutierrez2004** [sal-openlab/datafusion-server#1]
DataFusion has built-in support for Avro, any plans in DataFusion Server to support Avro format?

**Comment by neural-runner** [comment]
I appreciate your feedback. I understand the importance of Avro and was planning to support it based on demand; however, I will now include it in our immediate plans. Nonetheless, Avro support in DataFusion is an option controlled by a feature flag, as it affects binary size. As DataFusion Server, we also want to enable it based on usage, likely through a feature flag, probably `avro`.

**Comment by neural-runner** [comment]
We have added support for the Avro data source format. In this release, we only support loading. Due to the inability to collect many Avro files, testing was primarily conducted with `bin/data/popular-names.avro`.

* https://github.com/sal-openlab/datafusion-server/blob/main/CHANGELOG.md#0110-2024-04-18

We hope you find it useful. Please let us know if you encounter any issues or have any other feedback. Thank you.
